### ISSUE TITLE
Not showing the AutoComplete Menu

### ISSUE THREAD

**Issue by FilipeJInacio** [Ahmad45123/AutoCompleteMenu-ScintillaNET#11]
I was trying to style the AutoComplete Menu until I noticed that the Scintilla one doesn't even pop up. The one in Tester/ScintillaSample.

I took a look at the designer to see which words are currently list saved, but still, the Menu doesn't pop up.

What am I doing wrong?

**Comment by Ahmad45123** [comment]
Can you try again with the latest version on nuget? Also make sure you're using the newest Scintilla here: https://github.com/VPKSoft/Scintilla.NET

**Comment by FilipeJInacio** [comment]
Thank you, it is working now.
1 question, is there a way to configure the menu trigger?
It seems it only triggers at words bigger than 3.

**Comment by Ahmad45123** [comment]
CTRL+SPACE hotkey exists to trigger to open it. You can also just call the Open function to trigger it yourself programmaticly anytime.

**Comment by FilipeJInacio** [comment]
`this.AutoCompleteMenu.MinFragmentLength = 0;`
And thx for making this.
