### ISSUE TITLE
Is it possible to configure the tooltip?

### ISSUE THREAD

**Issue by FilipeJInacio** [Ahmad45123/AutoCompleteMenu-ScintillaNET#13]
This is the final result after using the AutoCompleteMenu:

![image](https://user-images.githubusercontent.com/102881633/218082667-1efd541b-fa73-4001-8f7f-691dc4e88276.png)

But I have some questions:

1) Is it possible to configure the tooltip colors?

2) Is there a automatic resazing of the AutoCompleteMenu depending on element size?

3) 

![IMG_20230210_144853](https://user-images.githubusercontent.com/102881633/218121495-fb4fc9b4-72c1-4e9a-9d5b-18c2366b3185.jpg)

Do you know why this happens?
Only happens when the program is open and rapidly corrects itself

**Comment by Ahmad45123** [comment]
Sorry for the delay again.. I just saw this :/

We can def add support to change colors of the tooltip. I'll push that later :) I'll also check the rest of the issues.

**Comment by Ahmad45123** [comment]
Should all be released now in https://github.com/Ahmad45123/AutoCompleteMenu-ScintillaNET/releases/tag/v2.1.0

Updated on NuGet too :)
