### ISSUE TITLE
AutoSize Error?

### ISSUE THREAD

**Issue by FilipeJInacio** [Ahmad45123/AutoCompleteMenu-ScintillaNET#15]
First of all, thanks for adding those new features.

I was trying AutoWidth and it wasn't working.

I tried taking a good look at the code and I think I found the error:

 - In the function UpdateSizeBasedOnVisible(), line 717 of AutoCompleteMenu.cs

where you have this:

`Host.CalcSize(Math.Min(MaximumSize.Width, mxWidth));`

and I think it should be this:

`Host.CalcSize(Math.Max(MaximumSize.Width, mxWidth));`

I'm opening this issue because after it gets the correct size this happens:

![image](https://user-images.githubusercontent.com/102881633/219944720-c58028ea-b736-4d02-8134-c7942747595f.png)

**Comment by Ahmad45123** [comment]
Make sure you have set MaximumSize to a good big value. The width in MaximumSize.

**Comment by Ahmad45123** [comment]
> Rusumingly, the AutoSizing works if it's smaller than the max size?

Yes but not exactly. The auto size does work but the width is simply limited to the width in the max size. If the visible words were smaller than the MaximumSize the actual width will be smaller but it's bounded by MaximumSize.Width.
