### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by sajithnechiparambil** [Ahmad45123/AutoCompleteMenu-ScintillaNET#5]
Please add column alignment for each column

Item selection using up or down key not working.

**Comment by Ahmad45123** [comment]
Implemented.

When declaring items set the Alignments property to the values needed. Look for the multicolumn sample code to check how its used.

**Comment by Ahmad45123** [comment]
Also I'm truly sorry for the huuuuuuuuge delay. I'm back maintaining this.
