### ISSUE TITLE
.NET version for AutoCompleteMenu-ScintillaNET...

### ISSUE THREAD

**Issue by cgm-wmaisenhelder** [Ahmad45123/AutoCompleteMenu-ScintillaNET#9]
Is there a version of this package available that supports .NET v4.5.2?

I am updating a massive .NET v4.5.2 project that used an old version of ScintillaNET.  I have successfully upgraded to Scintilla v5.3.1.3, with the exception of autocomplete support.

**Comment by Ahmad45123** [comment]
Not yet actually. I'l update it soon by next week latest.

**Comment by Ahmad45123** [comment]
Update pushed successfully on nuget.
